@ECHO OFF

REM ---------------------------------------------------------------------
REM the directory path to java.exe on your machine may be different
REM from the path I have between the double quotes below to this may
REM need to be changed in order for compile to work on your machine
REM ---------------------------------------------------------------------

"C:\Program Files\Java\jdk1.7.0_09\bin\java.exe" GameWindowApp
PAUSE
